version: '3.9'

networks:
  net:
    driver: bridge

services:
  chroma-server:
    image: server
    build:
      context: ../chroma
      dockerfile: Dockerfile
    volumes:
      - ../chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - 8000:8000
    networks:
      - net

  isaac-gpt-api-13b:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    restart: on-failure
    volumes:
      - './models:/models'
      - './api:/api'
    environment:
      MODEL: '/models/llama-2-13b-chat.bin'
      USE_MLOCK: 1
      MODEL_DOWNLOAD_URL: 'https://huggingface.co/TheBloke/Nous-Hermes-Llama2-GGML/resolve/main/nous-hermes-llama2-13b.ggmlv3.q4_0.bin'
    cap_add:
      - IPC_LOCK
    command: '/bin/sh /api/run.sh'
    networks:
      - net

  isaac-gpt-ui:
    build:
      context: ./ui 
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://isaac-gpt-api-13b:8000'
      - 'DEFAULT_MODEL=/models/llama-2-13b-chat.bin'
      - 'WAIT_HOSTS=isaac-gpt-api-13b:8000'
      - 'WAIT_TIMEOUT=600'
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
